---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: affinity-test
  region: us-east-2
  version: "1.21"
availabilityZones:
- us-east-2a
- us-east-2b
managedNodeGroups:
- name: on-demand
  instanceType: t3.small
  desiredCapacity: 1
  minSize: 1
  maxSize: 10
  volumeSize: 20
- name: spot
  instanceType: t3.small
  spot: true
  desiredCapacity: 1
  minSize: 1
  maxSize: 10
  volumeSize: 20