---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: pod-disruption-budget
  region: us-east-2
  version: "1.21"
availabilityZones:
- us-east-2a
- us-east-2b
managedNodeGroups:
- name: spot
  instanceType: t3.small
  spot: true
  desiredCapacity: 3
  minSize: 1
  maxSize: 10
  volumeSize: 20